google.maps.__gjsload__('geometry', function(_){var Ou=function(a,b){return Math.abs(_.ae(b-a,-180,180))},Pu=function(a,b,c,d,e){if(!d){c=Ou(a.lng(),c)/Ou(a.lng(),b.lng());if(!e)return e=Math.sin(_.Gc(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.Gc(b.lat())),_.Hc(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.O(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.Gc(a.lat());a=_.Gc(a.lng());d=_.Gc(b.lat());b=_.Gc(b.lng());c=_.Gc(c);return _.ae(_.Hc(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},Qu=function(){},Ru={containsLocation:function(a,b){var c=_.ae(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,q=l.getLength();m<q;++m){var r=l.getAt(m),v=l.getAt((m+1)%q),u=_.ae(r.lng(),-180,180),x=_.ae(v.lng(),-180,180),w=Math.max(u,x);u=Math.min(u,x);(180<w-u?c>=
w||c<u:c<w&&c>=u)&&Pu(r,v,c,d,f)<a.lat()&&(g=!g)}return g||Ru.isLocationOnEdge(a,b)}};_.Ua("PolyGeometry.containsLocation",Ru.containsLocation);
Ru.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.ae(a.lng(),-180,180),e=b instanceof _.ij,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),q=e?m:m-1,r=0;r<q;++r){var v=l.getAt(r),u=l.getAt((r+1)%m),x=_.ae(v.lng(),-180,180),w=_.ae(u.lng(),-180,180),A=Math.max(x,w),H=Math.min(x,w);if(x=1E-9>=Math.abs(_.ae(x-w,-180,180))&&(Math.abs(_.ae(x-d,-180,180))<=c||Math.abs(_.ae(w-d,-180,180))<=
c)){x=a.lat();w=Math.min(v.lat(),u.lat())-c;var L=Math.max(v.lat(),u.lat())+c;x=x>=w&&x<=L}if(x)return!0;if(180<A-H?d+c>=A||d-c<=H:d+c>=H&&d-c<=A)if(v=Pu(v,u,d,f,b),Math.abs(v-a.lat())<c)return!0}return!1};_.Ua("PolyGeometry.isLocationOnEdge",Ru.isLocationOnEdge);var Su={computeHeading:function(a,b){var c=_.Ce(a),d=_.De(a);a=_.Ce(b);b=_.De(b)-d;return _.ae(_.Hc(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Ua("Spherical.computeHeading",Su.computeHeading);
Su.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.Gc(c);var e=_.Ce(a);a=_.De(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.J(_.Hc(Math.asin(g)),_.Hc(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Ua("Spherical.computeOffset",Su.computeOffset);
Su.computeOffsetOrigin=function(a,b,c,d){c=_.Gc(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Ce(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.De(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.J(_.Hc(g),_.Hc(a))};
_.Ua("Spherical.computeOffsetOrigin",Su.computeOffsetOrigin);Su.interpolate=function(a,b,c){var d=_.Ce(a),e=_.De(a),f=_.Ce(b),g=_.De(b),h=Math.cos(d),k=Math.cos(f);b=Su.ng(a,b);var l=Math.sin(b);if(1E-6>l)return new _.J(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.J(_.Hc(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.Hc(Math.atan2(e,b)))};_.Ua("Spherical.interpolate",Su.interpolate);
Su.ng=function(a,b){var c=_.Ce(a);a=_.De(a);var d=_.Ce(b);b=_.De(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};Su.computeDistanceBetween=function(a,b,c){c=c||6378137;return Su.ng(a,b)*c};_.Ua("Spherical.computeDistanceBetween",Su.computeDistanceBetween);Su.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.Qg&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=Su.computeDistanceBetween(a[d],a[d+1],b);return c};
_.Ua("Spherical.computeLength",Su.computeLength);Su.computeArea=function(a,b){return Math.abs(Su.computeSignedArea(a,b))};_.Ua("Spherical.computeArea",Su.computeArea);Su.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.Qg&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=Su.Fk(c,a[e],a[e+1]);return d*b*b};_.Ua("Spherical.computeSignedArea",Su.computeSignedArea);Su.Fk=function(a,b,c){return Su.Gk(a,b,c)*Su.Fl(a,b,c)};
Su.Gk=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=Su.ng(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
Su.Fl=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.Ce(d);d=_.De(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var Tu={decodePath:function(a){for(var b=_.Xd(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.J(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Ua("PolylineCodec.decodePath",Tu.decodePath);
Tu.encodePath=function(a){a instanceof _.Qg&&(a=a.getArray());return Tu.Bn(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.Ua("PolylineCodec.encodePath",Tu.encodePath);Tu.Bn=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.Xd(a);f<g;++f)e=b?b(a[f]):a[f],Tu.hj(e[0]-d[0],c),Tu.hj(e[1]-d[1],c),d=e;return c.join("")};Tu.hj=function(a,b){Tu.Cn(0>a?~(a<<1):a<<1,b)};Tu.Cn=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.t.google.maps.geometry={encoding:Tu,spherical:Su,poly:Ru};_.n=Qu.prototype;_.n.decodePath=Tu.decodePath;_.n.encodePath=Tu.encodePath;_.n.computeDistanceBetween=Su.computeDistanceBetween;_.n.interpolate=Su.interpolate;_.n.computeHeading=Su.computeHeading;_.n.computeOffset=Su.computeOffset;_.n.computeOffsetOrigin=Su.computeOffsetOrigin;_.df("geometry",new Qu);});
