(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var c="Google \u00dcbersetzer",e=this||self;function f(a,l){a=a.split(".");var b=e;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===l?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=l}var g=/^[\w+/_-]+[=]{0,2}$/,h=null;function k(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&g.test(a)?a:""}function m(a){return a};var n={0:"\u00dcbersetzen",1:"Abbrechen",2:"Schlie\u00dfen",3:function(a){return"Google hat diese Seite automatisch in folgende Sprache \u00fcbersetzt: "+(a+".")},4:function(a){return"\u00dcbersetzt in: "+a},5:"Fehler: Der Server kann deine Anfrage momentan nicht verarbeiten. Bitte versuche es sp\u00e4ter noch einmal.",6:"Weitere Informationen",7:function(a){return"Powered by "+a},8:c,9:"\u00dcbersetzung wird erstellt.",10:function(a){return"Diese Seite mit Google \u00dcbersetzer in folgende Sprache \u00fcbersetzen: "+
(a+"?")},11:function(a){return"Diese Seite anzeigen auf: "+a},12:"Original anzeigen",13:"Der Content dieser lokal gespeicherten Datei wird \u00fcber eine sichere Verbindung zur \u00dcbersetzung an Google gesendet.",14:"Der Content dieser sicheren Seite wird \u00fcber eine sichere Verbindung zur \u00dcbersetzung an Google gesendet.",15:"Der Content dieser Intranetseite wird \u00fcber eine sichere Verbindung zur \u00dcbersetzung an Google gesendet.",16:"Sprache ausw\u00e4hlen",17:function(a){return"\u00dcbersetzung aus "+
(a+" deaktivieren")},18:function(a){return"Deaktivieren f\u00fcr: "+a},19:"Immer ausblenden",20:"Originaltext:",21:"Bessere \u00dcbersetzung vorschlagen",22:"Vorschlagen",23:"Alles \u00fcbersetzen",24:"Alles wiederherstellen",25:"Alles abbrechen",26:"Abschnitte in meine Sprache \u00fcbersetzen",27:function(a){return"Alles in folgende Sprache \u00fcbersetzen: "+a},28:"Originalsprachen anzeigen",29:"Optionen",30:"\u00dcbersetzung f\u00fcr diese Website deaktivieren",31:null,32:"Alternative \u00dcbersetzungen anzeigen",
33:"Klicke auf die oben stehenden W\u00f6rter, um alternative \u00dcbersetzungen abzurufen.",34:"Verwenden",35:"Zum Verschieben mit Umschalttaste ziehen",36:"Zum Aufrufen alternativer \u00dcbersetzungen klicken",37:"Halte Umschalttaste gedr\u00fcckt, klicke und ziehe dann die oben stehenden W\u00f6rter, um sie neu zu sortieren.",38:"Vielen Dank f\u00fcr deinen Vorschlag zu Google \u00dcbersetzer.",39:"\u00dcbersetzung f\u00fcr diese Website verwalten",40:"Klicke auf ein Wort, um alternative \u00dcbersetzungen zu sehen, oder klicke doppelt darauf, um es direkt zu bearbeiten.",
41:"Originaltext",42:c,43:"\u00dcbersetzen",44:"Deine Korrektur wurde gesendet.",45:"Fehler: Die Sprache der Webseite wird nicht unterst\u00fctzt.",46:'Widget "Sprache \u00fcbersetzen"'};var p;function q(a,l){this.a=l===r?a:""}var r={};var t=window.google&&google.translate&&google.translate._const;
if(t){var u;a:{for(var v=[],w=[""],x=0;x<w.length;++x){var y=w[x].split(","),z=y[0];if(z){var A=Number(y[1]);if(!(!A||.1<A||0>A)){var B=Number(y[2]),C=new Date,D=1E4*C.getFullYear()+100*(C.getMonth()+1)+C.getDate();!B||B<D||v.push({version:z,ratio:A,b:B})}}}var E=0,F=window.location.href.match(/google\.translate\.element\.random=([\d\.]+)/),G=Number(F&&F[1])||Math.random();for(x=0;x<v.length;++x){var H=v[x];E+=H.ratio;if(1<=E)break;if(G<E){u=H.version;break a}}u="TE_20201130_00"}var I="/element/%s/e/js/element/element_main.js".replace("%s",
u);if("0"==u){var J=" element %s e js element element_main.js".split(" ");J[J.length-1]="main_de.js";I=J.join("/").replace("%s",u)}if(t._cjlc)t._cjlc(t._pas+t._pah+I);else{var K=t._pas+t._pah+I,L,M="SCRIPT",N=document;M=String(M);"application/xhtml+xml"===N.contentType&&(M=M.toLowerCase());L=N.createElement(M);L.type="text/javascript";L.charset="UTF-8";var O,P;if(void 0===p){var Q=null,R=e.trustedTypes;if(R&&R.createPolicy){try{Q=R.createPolicy("goog#html",{createHTML:m,createScript:m,createScriptURL:m})}catch(a){e.console&&
e.console.error(a.message)}p=Q}else p=Q}var S=(P=p)?P.createScriptURL(K):K;O=new q(S,r);L.src=O instanceof q&&O.constructor===q?O.a:"type_error:TrustedResourceUrl";var T;var U=L.ownerDocument&&L.ownerDocument.defaultView;U&&U!=e?T=k(U.document):(null===h&&(h=k(e.document)),T=h);T&&L.setAttribute("nonce",T);var V=document.getElementsByTagName("head")[0];V||(V=document.body.parentNode.appendChild(document.createElement("head")));V.appendChild(L)}f("google.translate.m",n);f("google.translate.v",u)};}).call(window)
